sorted_array: sorted_array_main.o sorted_array.h
	g++ -o sorted_array sorted_array_main.o
sorted_array_main.o: sorted_array_main.cpp sorted_array.h
	g++ -c sorted_array_main.cpp
clean:
	rm sorted_array sorted_array_main.o
